### ISSUE TITLE
Conversion failed

### ISSUE THREAD

**Issue by ameyparanjape** [RobertBiehl/CLIP-tf2#1]
Hi, thank you for providing this conversion script. I am running into this error, not sure if what's the issue here:
```
Classify image: https://github.com/openai/CLIP/blob/main/CLIP.png?raw=true
Text options: ['a diagram', 'a dog', 'a cat', 'a neural network']
Pytorch: [[0.2441   0.003271 0.000827 0.752   ]]
Tensorflow: [[0.24351107 0.00320389 0.0008252  0.7524599 ]]
Traceback (most recent call last):
  File "convert_clip.py", line 64, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "convert_clip.py", line 40, in main
    converter.verify(FLAGS.model, model, image_url, text_options, verbose=True)
  File "/home/jupyter/CLIP-tf2/converter/convert.py", line 233, in verify
    assert np.abs(torch_probs - tf_probs).sum() < 1e-3, f"PyTorch and Tensorflow results should be almost equal: torch_probs={torch_probs}, tf_probs={tf_probs}"
AssertionError: PyTorch and Tensorflow results should be almost equal: torch_probs=[[0.2441   0.003271 0.000827 0.752   ]], tf_probs=[[0.24351107 0.00320389 0.0008252  0.7524599 ]]
```

My command looks like this:
`python convert_clip.py --model RN50 --output models/CLIP_{model}`

Any help would be appreciated, thanks!

**Comment by RobertBiehl** [comment]
Hi @ameyparanjape, this error doesn't seem too bad, as you can see the results are indeed almost equal.
You'd just need to increase the allowed error a bit in this line

https://github.com/RobertBiehl/CLIP-tf2/blob/main/converter/convert.py#L233

E.g. changing `assert np.abs(torch_probs - tf_probs).sum() < 1e-3` to `assert np.abs(torch_probs - tf_probs).sum() < 1e-2`.
Small numerical differences are expected between PyTorch and TF.

**Comment by ameyparanjape** [comment]
Thank you for replying @RobertBiehl , indeed I was able to get past that changing the threshold to `1e-2`. Just wanted to check if there is anything else that I was missing.
